### ISSUE TITLE
Predict - Confidence intervals

### ISSUE THREAD

**Issue by FransAndersen** [wbnicholson/BigVAR#14]
It would help me a lot if the predict function also returned the confidence intervals. Is this something that is planned?

**Comment by wbnicholson** [comment]
Yes, I will add these in the next release.  For now, you could obtain them via the following code (based on the formula from page 398 of [this link](https://faculty.washington.edu/ezivot/econ584/notes/varModels.pdf)):

```
library(BigVAR)
data(Y)
mod <- constructModel(Y,4,"Basic",c(50,10))
res <- cv.BigVAR(mod)
cis <- c(qnorm(.025),qnorm(.975))
# Extract residuals from BigVAR object to get an estimate of the covariance.
Sigma <- 1/nrow(Y-p*ncol(Y))*diag(sqrt(crossprod(res@resids)))
lower <- predict(res,n.ahead = 1)+cis[1]*Sigma
upper <- predict(res,n.ahead = 1)+cis[2]*Sigma
```

**Comment by FransAndersen** [comment]
Thank you @wbnicholson!

**Comment by wbnicholson** [comment]
This has been added to predict in [9aacdce](https://github.com/wbnicholson/BigVAR/commit/9aacdcea96438d69fc6e90ecf5229b41863b91c9) with option confint.
