### ISSUE TITLE
In-sampe estimation without cross-validation

### ISSUE THREAD

**Issue by FransAndersen** [wbnicholson/BigVAR#19]
Is there any function that could help me fit a model without cross-validation which chooses the lambda value to minimize in-sample MSFE on the whole dataset?

I tried to fit a BigVAR model on the whole dataset without cross-validation running BigVAR.est. It returns 10 lambda and coefficient matrixes. I see in the manual that "This method allows the user to construct their own penalty parameter selection procedure.". So I then need to predict and calculate accuracy based on this to choose the best lambda
Is there any easier method? I've tried to modify T1 and T2 for cv.BigVAR without success

**Why fitting a model without cross-validation?**
I have a COVID-effect on the last 12 observations in the data and therefore added an exogen blip dummy to filter this effect out, however, since the dummy is at the end of the time series the coefficient for the dummy after running cv.BigVAR is 0, since the dummy is located in the forecast evaluation section.
![image](https://user-images.githubusercontent.com/15922694/121183022-eb4de400-c863-11eb-812c-e77149330fdf.png)

**Comment by FransAndersen** [comment]
Another idea; run cv.BigVAR take @OptimalLambda and use it BigVAR.fit() on the whole dataset

**Comment by wbnicholson** [comment]
You could try something similar to the n-fold CV approach described [in the BigVAR guide](http://www.wbnicholson.com/BigVAR.html#n-fold-cross-validation).

**Comment by FransAndersen** [comment]
Thank you @wbnicholson!
