### ISSUE TITLE
Predict with VARX returns error in VARXCons

### ISSUE THREAD

**Issue by Blaieet** [wbnicholson/BigVAR#20]
Hi,

First of all, thank you for this great package. 

Second, I have a penalized VARX model and I want to perform a forecast of 10 periods ahead. The model consists of 17 endogenous variables and 34 exogenous variables. I'm specifying:

`predict(BV,10,newxreg=test[ , (num.endogenous):ncol(test)])`

And I'm getting the following error:

```
Error in VARXCons(as.matrix(Y), X, ncol(Y), p, m, s, oos = TRUE) : 
  Not compatible with requested type: [type=list; target=double]
```

It seems there's a variable type error inside the C++ function VARXCons. Any suggestion of what could be the problem?

Thanks!

**Comment by wbnicholson** [comment]
Is test stored as a matrix?  If you can post the data or something similar I can take a closer look at it.

**Comment by Blaieet** [comment]
Hi again!

Casting this exogenous variables to matrix:

`predict(BV,10,newxreg=as.matrix(test[ , (num.endogenous):ncol(test)]))`

Solves the issue!

Thanks you again 😊
