### ISSUE TITLE
python README: variable k not declared

### ISSUE THREAD

**Issue by extrospective** [wbnicholson/BigVAR#21]
k=3 declaration occurs after first use of k.

propose to shift up in the README.

I wonder if the sample code should be included in the repo.
Also the file does not follow PEP8, so I could tweak the code to follow python standards when making pull request.

**Comment by wbnicholson** [comment]
It has been corrected [https://github.com/wbnicholson/BigVAR/commit/8fd3944ea5ac29b6db10a875ec4bbcb7114fa180](https://github.com/wbnicholson/BigVAR/commit/8fd3944ea5ac29b6db10a875ec4bbcb7114fa180)
