### ISSUE TITLE
BigVAR.fit not respecting VARX$contemp = FALSE

### ISSUE THREAD

**Issue by jonlachmann** [wbnicholson/BigVAR#29]
When I use ```BigVAR.fit``` to fit a model, I may have a VARX list on the form ```list(k=2, s=1, s1=0, contemp=FALSE)```. Then, ```BigVAR.fit``` will run the following code:

```
if (!is.null(VARX$contemp)) {
  contemp <- TRUE
  s1 <- 1
} else {
  contemp <- FALSE
  s1 <- 0
}
```

This will then, erroneously set ```contemp``` to ```TRUE```, and the accompanying parameter ```s1``` to ```1```. I would expect it to respect that I have chosen to not have contemporaneous interaction of the exogenous variables if I set it to FALSE.

Another question, which relates to this, is why does EFX not support ```contemp=TRUE```?

**Comment by wbnicholson** [comment]
Thanks, this has been fixed.  

Regarding EFX not supporting contemp=TRUE, my reasoning was that since the EFX shrinks from a VARX to a VAR it didn't make sense to allow contemporaneous exogenous coefficients since there is no corresponding VAR coefficient to shrink toward.

**Comment by jonlachmann** [comment]
Nice! Thank you!

And that explanation makes sense, thanks!
