### ISSUE TITLE
BigVAR.fit failing with "Forecast Horizon too long; increase T1 or decrease h".

### ISSUE THREAD

**Issue by jonlachmann** [wbnicholson/BigVAR#34]
Hi!

When using the BigVAR.fit function, explicitly without using any cross validation, when I have short data I get the error ```Forecast Horizon too long; increase T1 or decrease h```. This appears to be wrong as I would not care about the values of T1 or T2 when I dont want to run any cross validation.

Upon inspecting the code I see that a call to ```constructModel``` to create a variable called ```temp.bv``` is created and never used. Is the intention here to perform some general checks on the model before allowing it to be fit? Or is it just something that can be removed?

See the code here: https://github.com/wbnicholson/BigVAR/blob/07bdaeac7086d9f669a51bd338f01ddeb548a7c4/BigVAR/R/BigVARFitFun.R#L281-L282

I would be happy to provide a PR removing that line, or fixing the issue in another way, I mainly need some advice on how to proceed so that the intentions of the code are preserved.

**Comment by wbnicholson** [comment]
Thanks, that will work.  In this context, constructModel is used as a wrapper to construct a BigVAR object and check its validity.  I set cv to "LOO" which is less restrictive but it appears a third option is warranted.  I will push your commits over the weekend.

**Comment by jonlachmann** [comment]
> Thanks, that will work. In this context, constructModel is used as a wrapper to construct a BigVAR object and check its validity. I set cv to "LOO" which is less restrictive but it appears a third option is warranted. I will push your commits over the weekend.

Thanks for clarifying, I saw a comment in the code after posting, pointing to that being the case.

Sounds great with some pushes during the weekend, let me know if there are any issues I can assist with. Would it be possible to push a new version to CRAN when everything is merged?

**Comment by wbnicholson** [comment]
Yes, I'll start to prepare an update for cran in the next few weeks.

**Comment by jonlachmann** [comment]
I created a PR for this fix as well now. Please have a look at it when you get the time so we can get it merged as well.

**Comment by wbnicholson** [comment]
This commit has been pushed

**Comment by jonlachmann** [comment]
Hi! Thanks, I saw you added a few lines in https://github.com/wbnicholson/BigVAR/commit/86a3c6e7b0d86b0758f4aa3674c55792bf387b7c, however, there is a typo where it looks at "ctype" and not "cvtype" in the if statement.

**Comment by wbnicholson** [comment]
Thanks fixed that in [f571b76](https://github.com/wbnicholson/BigVAR/commit/f571b76fdfa966a0aa595fd60b8d258caf3c514a)

**Comment by jonlachmann** [comment]
Great, closing the issue then!
